// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJO6QjWmn_mhD62j1It0XaMFG0GgMLc8c',
    appId: '1:444466216257:web:8f62b798003e3ff6bb35c0',
    messagingSenderId: '444466216257',
    projectId: 'cobafirebaseandroid',
    authDomain: 'cobafirebaseandroid.firebaseapp.com',
    databaseURL: 'https://cobafirebaseandroid.firebaseio.com',
    storageBucket: 'cobafirebaseandroid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzFEniQL_cEOw1-rNlXN6cG_vLVBFCPgE',
    appId: '1:444466216257:android:512c3d6da99e4b36bb35c0',
    messagingSenderId: '444466216257',
    projectId: 'cobafirebaseandroid',
    databaseURL: 'https://cobafirebaseandroid.firebaseio.com',
    storageBucket: 'cobafirebaseandroid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnhO_jZZ8BPiDG6XUrrC0EltLoSpyj5jg',
    appId: '1:444466216257:ios:f2a0364b77c1d3abbb35c0',
    messagingSenderId: '444466216257',
    projectId: 'cobafirebaseandroid',
    databaseURL: 'https://cobafirebaseandroid.firebaseio.com',
    storageBucket: 'cobafirebaseandroid.appspot.com',
    iosClientId: '444466216257-sb35m2n03drt69oft4h1tlb5q3m9hakl.apps.googleusercontent.com',
    iosBundleId: 'com.example.denahTest',
  );
}
